# Game settings
MAX_LEVELS = 10
TILE_SIZE = 40
PLAYER_SIZE = TILE_SIZE - 10
GOAL_SIZE = TILE_SIZE - 10
ENEMY_SIZE = TILE_SIZE - 10
ITEM_SIZE = TILE_SIZE - 10
KEY_SIZE = TILE_SIZE - 10
JOURNAL_SIZE = TILE_SIZE - 10
LEVER_SIZE = TILE_SIZE - 10
ARCHIVE_SIZE = TILE_SIZE - 10
SURVIVOR_SIZE = TILE_SIZE - 10
LEVER_PUZZLE_SIZE = TILE_SIZE - 10

# Screen layout
GAME_SCREEN_HEIGHT_RATIO = 0.75

# Player settings
PLAYER_SPEED = 5
INITIAL_ECHO_USES = 3
ECHO_DURATION = 3.0
INITIAL_TORCH_BATTERY = 100.0

# Enemy settings
BASE_ENEMY_SPEED = 1.6
ENEMY_SPEED_LEVEL_MULTIPLIER = 0.12
ENEMY_SPEED_WRONG_LEVER_MULTIPLIER = 1.12

# Difficulty settings
NORMAL_DRAIN_ACTIVE = 0.0
NORMAL_DRAIN_IDLE = 0.0
NORMAL_ENEMY_MULTIPLIER = 1.0
HARD_DRAIN_ACTIVE = 12.0
HARD_DRAIN_IDLE = 1.0
HARD_ENEMY_MULTIPLIER = 1.0
EXTREME_DRAIN_ACTIVE = 12.0
EXTREME_DRAIN_IDLE = 1.0
EXTREME_ENEMY_MULTIPLIER = 1.35

# Maze generation
INITIAL_MAZE_DENSITY = 0.25
MAZE_DENSITY_LEVEL_MULTIPLIER = 0.02
MAX_MAZE_DENSITY = 0.45

# Update rate
UPDATE_RATE = 1/60

# Story events
LEVEL_4_SAFE_SPEED_MULTIPLIER = 0.9
LEVEL_4_FAST_SPEED_MULTIPLIER = 1.2
TORCH_DRAIN_MULTIPLIER_LEVEL_6 = 1.6

# Colors
COLOR_BLACK = (0, 0, 0, 1)
COLOR_MAZE_WALL = (0.12, 0.12, 0.12, 1)
COLOR_KEY = (1, 0.6, 0, 1)
COLOR_GOAL = (0, 1, 0.4, 1)
COLOR_ENEMY = (1, 0.2, 0.2, 1)
COLOR_ITEM = (1, 1, 0, 1)
COLOR_JOURNAL = (0, 0.8, 0.8, 1)
COLOR_LEVER = (0.6, 0.3, 1, 1)
COLOR_ARCHIVE = (1, 1, 1, 1)
COLOR_SURVIVOR = (0.7, 0.7, 1, 1)
COLOR_LEVER_PUZZLE_WRONG = (0.8, 0.5, 1, 1)
COLOR_LEVER_PUZZLE_CORRECT = (0.5, 1, 0.8, 1)
COLOR_PLAYER = (0.2, 0.5, 1, 1)
COLOR_DARKNESS = (0.1, 0.1, 0.1, 1)
